spec:
  name: vib3-web
  region: nyc
  services:
  - name: web
    environment_slug: node-js
    github:
      repo: Vibe-Hacker/vib3-web
      branch: main
      deploy_on_push: true
    build_command: npm install
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: professional-xs
    envs:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      value: mongodb+srv://vib3user:vib3123@vib3cluster.mongodb.net/vib3?retryWrites=true&w=majority
      type: SECRET
    - key: DO_SPACES_KEY
      value: DO00RUBQWDCCVRFEWBFF
      type: SECRET
    - key: DO_SPACES_SECRET
      value: 05J/3Y+QIh5a83Eag5rFxnp4RNhNOqfwVNUjbKNuqn8
      type: SECRET
    - key: DO_SPACES_BUCKET
      value: vib3-videos
    - key: DO_SPACES_REGION
      value: nyc3
    - key: PORT
      value: "3000"